"""Rule for assembling a runnable PostgreSQL installation tree."""

def _directory_output_impl(ctx):
    out = ctx.actions.declare_directory(ctx.attr.dirname or ctx.label.name)
    cmd = ctx.expand_location(
        ctx.attr.cmd,
        targets = ctx.attr.srcs + ctx.attr.tools,
    ).replace("{out}", out.path)
    ctx.actions.run_shell(
        inputs = depset(ctx.files.srcs),
        tools = ctx.files.tools,
        outputs = [out],
        command = cmd,
        use_default_shell_env = True,
        progress_message = "Assembling %s" % ctx.label.name,
    )
    return [DefaultInfo(files = depset([out]), runfiles = ctx.runfiles(files = [out]))]

directory_output = rule(
    implementation = _directory_output_impl,
    doc = """Runs a shell command that populates one output directory.

`cmd` is $(location)-expanded over srcs+tools, and `{out}` is replaced with
the output directory path.""",
    attrs = {
        "cmd": attr.string(mandatory = True),
        "dirname": attr.string(),
        "srcs": attr.label_list(allow_files = True),
        "tools": attr.label_list(allow_files = True, cfg = "exec"),
    },
)

_LAUNCHER = """#!/bin/bash
# Generated by pg_wrapper. Runs one binary out of a pg_dist tree with the
# tree's bin/ as its directory, which is what makes postgres find share/.

# --- bazel runfiles bootstrap ---
# Deliberately before `set -e`: the snippet probes several locations and
# relies on the failures falling through the || chain.
# shellcheck disable=SC1090,SC1091
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${{RUNFILES_DIR:-/dev/null}}/$f" 2>/dev/null || \\
  source "$(grep -sm1 "^$f " "${{RUNFILES_MANIFEST_FILE:-/dev/null}}" | cut -f2- -d' ')" 2>/dev/null || \\
  source "$0.runfiles/$f" 2>/dev/null || \\
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \\
  {{ echo >&2 "ERROR: cannot find $f"; exit 1; }}
# --- end runfiles bootstrap ---
set -euo pipefail

dist=$(rlocation "{dist}")
if [ -z "$dist" ] || [ ! -d "$dist" ]; then
    echo >&2 "pg_wrapper: no dist tree at {dist}"
    exit 1
fi
exec "$dist/bin/{binary}" "$@"
"""

def _rlocationpath(ctx, file):
    if file.short_path.startswith("../"):
        return file.short_path[len("../"):]
    return "{}/{}".format(ctx.workspace_name, file.short_path)

def _pg_wrapper_impl(ctx):
    launcher = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.write(
        output = launcher,
        content = _LAUNCHER.format(
            binary = ctx.attr.binary,
            # short_path for an external file already carries ../<repo>/,
            # so let bazel spell the runfiles path instead of building it.
            dist = _rlocationpath(ctx, ctx.file.dist),
        ),
        is_executable = True,
    )
    runfiles = ctx.runfiles(files = [ctx.file.dist])
    runfiles = runfiles.merge(ctx.attr._runfiles_lib[DefaultInfo].default_runfiles)
    return [DefaultInfo(executable = launcher, runfiles = runfiles)]

pg_wrapper = rule(
    implementation = _pg_wrapper_impl,
    doc = """An executable that runs one binary from a pg_dist tree.

Saves callers from spelling out `$(location //:pg_dist)/bin/psql` and from
staging the tree themselves: `bazel run @postgres_18_4//:psql_bin` just works,
and the target can be used as a tool or in a test's `data`.""",
    executable = True,
    attrs = {
        "binary": attr.string(
            mandatory = True,
            doc = "Name under the dist tree's bin/, e.g. \"psql\".",
        ),
        "dist": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "The pg_dist directory target.",
        ),
        "_runfiles_lib": attr.label(default = "@bazel_tools//tools/bash/runfiles"),
    },
)
