module(name = "postgres_test_builds")

bazel_dep(name = "postgres_bazel")
local_path_override(
    module_name = "postgres_bazel",
    path = "../postgres_bazel",
)

postgres = use_extension("@postgres_bazel//:extension.bzl", "postgres")
postgres.add_version(version = "18.4")
use_repo(postgres, "postgres_18_4", "postgres_config")
